spring.application.name=HoqueiBrasil

# Configuração do Banco de Dados em um serviço gerenciado na nuvem
spring.datasource.url=jdbc:postgresql://localhost:5432/HoqueiBrasil
spring.datasource.username=admin_cbhp
spring.datasource.password=123456

# Configurações de JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Configurações do Spring Cloud (se aplicável)
#spring.cloud.config.uri=http://<config-server-url>